# Generated by Django 5.0.3 on 2024-03-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
